### ISSUE TITLE
feat: [samuray90] [pug-scss] badges of different colors #35

### ISSUE THREAD

**Issue by samuray90** [codetapacademy/master-agile#38]
**Original** from  feat: badges of different colors #35

**Comment by samuray90** [comment]
![badge](https://user-images.githubusercontent.com/47028775/79702950-5c1cf000-82a0-11ea-8080-c22f6d9dd14e.PNG)

**Comment by samuray90** [comment]
Hi, please write your suggestions here ( for example I would like to position the badges inside of a box).

**Comment by marianzburlea** [comment]
Good play @samuray90 

You might want to have a look at:
https://github.com/codetapacademy/master-agile/blob/master/_resources/badge.xd?raw=true
